[project]
protostar-version = "0.9.0"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "src",
]

[contracts]
ERC3525Full = ["./src/carbonable/erc3525/presets/ERC3525Full.cairo"]
ERC3525MintableBurnable = ["./src/carbonable/erc3525/presets/ERC3525MintableBurnable.cairo"]
ERC3525SlotApprovable = ["./src/carbonable/erc3525/presets/ERC3525SlotApprovable.cairo"]
ERC3525SlotEnumerableMintableBurnable = ["./src/carbonable/erc3525/presets/ERC3525SlotEnumerableMintableBurnable.cairo"]
