["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
erc3525 = [
    "./src/carbonable/erc3525/ERC3525.cairo",
]

["protostar.shared_command_configs"]
cairo_path = [
    "./lib/cairo_contracts/src",
    "src"
]